name: Generate the Website!

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # ---------------------------------
      # Setup

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # ---------------------------------
      # someran.dev

      - name: Copy Main Page to `public/`
        run: cp ./index.html ./public/index.html

      # ---------------------------------
      # someran.dev/links

      - name: Install Links Dependencies
        run: deno install
        working-directory: "links"

      - name: Generate Links HTML File
        run: deno run generate_html
        working-directory: "links"

      - name: Build Links Site
        run: deno run build
        working-directory: "links"

      - name: Copy Links Page to `public/`
        run: cp -a ./links/dist/. ./public/links/

      # ---------------------------------
      # someran.dev/rpgmaker

      - name: Install RPG Maker Website Dependencies
        run: deno install
        working-directory: "rpgmaker"

      - name: Build RPG Maker Website
        run: deno run start
        working-directory: "rpgmaker"

      - name: Copy RPG Maker Website to `public/`
        run: cp -a ./rpgmaker/public/. ./public/rpgmaker/

      # ---------------------------------
      # Upload website

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
